---
swagger: "2.0"
info:
  version: "0.0.0"
  title: "NewshubAPIV2"
host: "dsnewsapi.sphdigital.com"
basePath: "/v2"
tags:
  - name: st-feed
  - name: st-discover
  - name: push
schemes:
  - "https"
securityDefinitions:
  api_key:
    type: "apiKey"
    name: "x-api-key"
    in: "header"
x-amazon-apigateway-gateway-responses:
  WAF_FILTERED:
    statusCode: 403
    responseTemplates:
      application/json: "{\"code\": 403,\"message\": \"APIGW: WAF Filtered\",\"data\"\
        : null}"
  ACCESS_DENIED:
    statusCode: 403
    responseTemplates:
      application/json: "{\"code\": 403,\"message\": \"APIGW: Access Denied\",\"data\"\
        : null}"
  INVALID_API_KEY:
    statusCode: 403
    responseTemplates:
      application/json: "{\"code\": 403,\"message\": \"APIGW: Invalid API Key\",\"\
        data\": null}"
  MISSING_AUTHENTICATION_TOKEN:
    statusCode: 403
    responseTemplates:
      application/json: "{\"code\": 403,\"message\": \"APIGW: Unsupported API method\
        \ or resource\",\"data\": null}"
  DEFAULT_4XX:
    responseTemplates:
      application/json: "{\"code\": 403,\"message\": \"APIGW: Request Not Allowed\"\
        ,\"data\": null}"
  EXPIRED_TOKEN:
    statusCode: 403
    responseTemplates:
      application/json: "{\"code\": 403,\"message\": \"APIGW: Configuration - Expired\
        \ Token\",\"data\": null}"
  INVALID_SIGNATURE:
    statusCode: 403
    responseTemplates:
      application/json: "{\"code\": 403,\"message\": \"APIGW - Invalid Signature\"\
        ,\"data\": null}"
        
consumes:
  - application/json
definitions:
  ClearSessionResponseBody:
    properties:
      code:
        format: int64
        type: integer
      message:
        type: string
    type: object
  ClearUserSessionRequestBody:
    description: |-
      A ClearUserSessionRequestBody model
      this is used for clearing user session
    properties:
      username:
        type: string
    required:
      - username
    type: object
  Devices:
    description: 'Devices : Device model'
    properties:
      appName:
        type: string
      appVersion:
        type: string
      deviceId:
        type: string
      deviceName:
        type: string
      mobilePackage:
        type: string
      osName:
        type: string
      osVersion:
        type: string
    type: object
  InAppVerifyRequestBody:
    description: A Verify device parameter model
    properties:
      deviceId:
        type: string
      receiptData:
        type: string
      serviceCode:
        type: string
    required:
      - receiptData
      - deviceId
    type: object
  InAppWebhook:
    properties:
      latest_receipt_info:
        $ref: '#/definitions/LatestReceipt'
      notification_type:
        type: string
    required:
      - latest_receipt_info
    type: object
  LatestReceipt:
    properties:
      expires_date:
        type: string
      original_transaction_id:
        type: string
    required:
      - original_transaction_id
      - expires_date
    type: object
  ListResponse:
    properties:
      code:
        format: int64
        type: integer
      data:
        items:
          $ref: '#/definitions/Product'
        type: array
      message:
        type: string
    type: object
  LoginResponseBody:
    properties:
      code:
        format: int64
        type: integer
      data:
        $ref: '#/definitions/TokenData'
      message:
        type: string
    type: object
  LogoutResponseBody:
    properties:
      code:
        format: int64
        type: integer
      data:
        items:
          type: object
        type: array
      message:
        type: string
    type: object
  MySPHCheckDeviceResponseBody:
    properties:
      code:
        format: int64
        type: integer
      data:
        items:
          $ref: '#/definitions/Devices'
        type: array
      message:
        type: string
    type: object
  MySPHLoginRequestBody:
    description: |-
      A MySPHLoginRequestBody model
      this is used for request to login to MySPH
    properties:
      appName:
        type: string
      appVersion:
        type: string
      deviceCode:
        type: string
      deviceId:
        type: string
      deviceName:
        type: string
      osName:
        type: string
      osVersion:
        type: string
      password:
        type: string
      serviceCode:
        type: string
      username:
        type: string
    required:
      - username
      - password
      - deviceCode
      - deviceId
      - deviceName
      - osName
      - osVersion
      - appName
      - appVersion
      - serviceCode
    type: object
  MySPHLogoutRequest:
    description: |-
      A MySPHLogoutRequest model
      this is used for request to logout from MySPH
    properties:
      deviceId:
        type: string
    type: object
  MySPHRegisterRequestBody:
    description: |-
      A MySPHRegisterRequestBody model
      this is used for request to register MySPH account
    properties:
      firstName:
        type: string
      goto:
        type: string
      lastName:
        type: string
      password:
        type: string
      serviceFlag:
        type: string
      username:
        type: string
    required:
      - username
      - password
      - firstName
      - lastName
      - serviceFlag
      - goto
    type: object
  Product:
    description: Product Model
    properties:
      description:
        type: string
      productId:
        type: string
    type: object
  RegisterResponseBody:
    properties:
      code:
        format: int64
        type: integer
      data:
        $ref: '#/definitions/RegistrationData'
      message:
        type: string
    type: object
  RegistrationData:
    properties:
      systemId:
        type: string
    type: object
  Response:
    description: 'Response : Response model'
    properties:
      aoVisitorId:
        type: string
      devices:
        items:
          $ref: '#/definitions/Devices'
        type: array
      message:
        type: string
      premium_token:
        type: string
      resultCode:
        type: string
      servicecode:
        type: string
      status:
        format: int64
        type: integer
    type: object
  TokenData:
    properties:
      aoVisitorId:
        type: string
      contactKey:
        type: string
      emailAddress:
        type: string
      gaUserType:
        format: int64
        type: integer
      mySPHID:
        type: string
      pushSegments:
        items:
          type: string
        type: array
      serviceflags:
        type: string
      services:
        items:
          $ref: '#/definitions/Response'
        type: array
      token:
        type: string
      userType:
        type: string
    type: object
  TokenLoginRequestBody:
    description: |-
      A TokenLoginRequestBody model
      this is used for token login e.g. Google, Facebook etc.
    properties:
      appName:
        type: string
      appVersion:
        type: string
      deviceCode:
        type: string
      deviceId:
        type: string
      deviceName:
        type: string
      osName:
        type: string
      osVersion:
        type: string
      serviceCode:
        type: string
      token:
        type: string
    required:
      - token
      - deviceCode
      - deviceId
      - deviceName
      - osName
      - osVersion
      - appName
      - appVersion
      - serviceCode
    type: object
  WebhookResponseBody:
    properties:
      code:
        format: int64
        type: integer
      data:
        items:
          type: object
        type: array
      message:
        type: string
    type: object
host: localhost
info:
  description: Newshub authentication api.
  title: newshub-auth-api
  version: 0.0.1
paths:
  /auth/in-app/device:
    get:
      description: |-
        Login with registered device id
        [Github Repo](https://github.com/SPHTech/newshub-auth-api/blob/e9ba4f9fdaaf36e03feb0390be4d72cde25b747c/internal/router/router.go#L130)
        [Confluence Docs](https://sph.atlassian.net/wiki/spaces/MB/pages/8713106/Microservice+Inapp+Purchase+API+Design)
      operationId: inAppDevice
      parameters:
        - in: header
          name: authorization
          required: true
          type: string
      responses:
        "200":
          $ref: '#/responses/LoginResponse'
      security:
        - api_key: []
      tags:
        - auth
  /auth/in-app/products/{pub}/{device}:
    get:
      description: |-
        GetProductList call to get Product Listing based on PublicationCode and Device(iphone/ipad)
        [Github Repo](https://github.com/SPHTech/newshub-auth-api/blob/e9ba4f9fdaaf36e03feb0390be4d72cde25b747c/internal/router/router.go#L111)
        [Confluence Docs](https://sph.atlassian.net/wiki/spaces/MB/pages/8713106/Microservice+Inapp+Purchase+API+Design)
      operationId: GetProductList
      parameters:
        - in: path
          name: pub
          required: true
          type: string
        - in: path
          name: device
          required: true
          type: string
        - in: query
          name: region
          type: string
      responses:
        "200":
          $ref: '#/responses/GetProductList'
      security:
        - api_key: []
      tags:
        - getProductList
  /auth/in-app/verify:
    post:
      description: |-
        Login with in-app purchase data
        [Github Repo](https://github.com/SPHTech/newshub-auth-api/blob/e9ba4f9fdaaf36e03feb0390be4d72cde25b747c/internal/router/router.go#L119)
        [Confluence Docs](https://sph.atlassian.net/wiki/spaces/MB/pages/8713106/Microservice+Inapp+Purchase+API+Design)
      operationId: inAppVerifyReceipt
      parameters:
        - in: body
          name: Body
          schema:
            $ref: '#/definitions/InAppVerifyRequestBody'
      responses:
        "200":
          $ref: '#/responses/LoginResponse'
      security:
        - api_key: []
      tags:
        - auth
  /auth/in-app/webhook:
    post:
      description: |-
        Webhook call server to server Notification
        [Github Repo](https://github.com/SPHTech/newshub-auth-api/blob/e9ba4f9fdaaf36e03feb0390be4d72cde25b747c/internal/router/router.go#L120)
        [Confluence Docs](https://sph.atlassian.net/wiki/spaces/MB/pages/8713106/Microservice+Inapp+Purchase+API+Design)
      operationId: inAppWebhook
      parameters:
        - in: body
          name: Body
          schema:
            $ref: '#/definitions/InAppWebhook'
      responses:
        "200":
          $ref: '#/responses/WebhookResponse'
      tags:
        - auth
  /auth/my-sph/check-device:
    get:
      description: |-
        Check device for MySPH User
        [Github Repo](https://github.com/SPHTech/newshub-auth-api/blob/e9ba4f9fdaaf36e03feb0390be4d72cde25b747c/internal/router/router.go#L129)
        [Confluence Docs](https://sph.atlassian.net/wiki/spaces/MB/pages/8713091/Microservice+Login+Logout+Check+Device+Service+Design)
      operationId: mySPHCheckDevice
      parameters:
        - in: header
          name: authorization
          required: true
          type: string
      responses:
        "200":
          $ref: '#/responses/MySPHCheckDeviceResponse'
      security:
        - api_key: []
      tags:
        - auth
  /auth/my-sph/facebooklogin:
    post:
      description: |-
        FacebookLogin to My SPH
        [Github Repo](https://github.com/SPHTech/newshub-auth-api/blob/e9ba4f9fdaaf36e03feb0390be4d72cde25b747c/internal/router/router.go#L118)
        [Confluence Docs](https://sph.atlassian.net/wiki/spaces/MB/pages/604964163/Microservice+Facebook+Login)
      operationId: facebookLogin
      parameters:
        - in: body
          name: Body
          schema:
            $ref: '#/definitions/TokenLoginRequestBody'
      responses:
        "200":
          $ref: '#/responses/LoginResponse'
      security:
        - api_key: []
      tags:
        - auth
  /auth/my-sph/googlelogin:
    post:
      description: |-
        GoogleLogin to My SPH
        [Github Repo](https://github.com/SPHTech/newshub-auth-api/blob/e9ba4f9fdaaf36e03feb0390be4d72cde25b747c/internal/router/router.go#L117)
        [Confluence Docs](https://sph.atlassian.net/wiki/spaces/MB/pages/143950344/Microservice+Google+Login)
      operationId: googleLogin
      parameters:
        - in: body
          name: Body
          schema:
            $ref: '#/definitions/TokenLoginRequestBody'
      responses:
        "200":
          $ref: '#/responses/LoginResponse'
      security:
        - api_key: []
      tags:
        - auth
  /auth/my-sph/login:
    post:
      description: |-
        Login to My SPH
        [Github Repo](https://github.com/SPHTech/newshub-auth-api/blob/e9ba4f9fdaaf36e03feb0390be4d72cde25b747c/internal/router/router.go#L114)
        [Confluence Docs](https://sph.atlassian.net/wiki/spaces/MB/pages/8713091/Microservice+Login+Logout+Check+Device+Service+Design)
      operationId: mySphLogin
      parameters:
        - in: body
          name: Body
          schema:
            $ref: '#/definitions/MySPHLoginRequestBody'
      responses:
        "200":
          $ref: '#/responses/LoginResponse'
      security:
        - api_key: []
      tags:
        - auth
  /auth/my-sph/logout:
    post:
      description: |-
        Logout from My SPH
        [Github Repo](https://github.com/SPHTech/newshub-auth-api/blob/e9ba4f9fdaaf36e03feb0390be4d72cde25b747c/internal/router/router.go#L137)
        [Confluence Docs](https://sph.atlassian.net/wiki/spaces/MB/pages/8713091/Microservice+Login+Logout+Check+Device+Service+Design)
      operationId: mySPHLogout
      parameters:
        - in: header
          name: authorization
          required: true
          type: string
        - in: body
          name: Body
          schema:
            $ref: '#/definitions/MySPHLogoutRequest'
      responses:
        "200":
          $ref: '#/responses/LogoutResponse'
      security:
        - api_key: []
      tags:
        - auth
  /auth/my-sph/register:
    post:
      description: |-
        Register My SPH account
        [Github Repo](https://github.com/SPHTech/newshub-auth-api/blob/e9ba4f9fdaaf36e03feb0390be4d72cde25b747c/internal/router/router.go#L116)
        [Confluence Docs](https://sph.atlassian.net/wiki/spaces/MB/pages/93421577/Microservice+mySPH+Account+Register+Endpoint)
      operationId: mySphRegister
      parameters:
        - in: body
          name: Body
          schema:
            $ref: '#/definitions/MySPHRegisterRequestBody'
      responses:
        "200":
          $ref: '#/responses/RegisterResponse'
      security:
        - api_key: []
      tags:
        - auth
  /auth/my-sph/session:
    delete:
      description: |-
        Clear user session by username
        [Github Repo](https://github.com/SPHTech/newshub-auth-api/blob/e9ba4f9fdaaf36e03feb0390be4d72cde25b747c/internal/router/router.go#L123)
        [Confluence Docs](https://sph.atlassian.net/wiki/spaces/MB/pages/1142391308/Clear+User+Session+Endpoint)
      operationId: clearUserSession
      parameters:
        - in: body
          name: Body
          schema:
            $ref: '#/definitions/ClearUserSessionRequestBody'
      responses:
        "200":
          $ref: '#/responses/ClearSessionResponse'
      security:
        - api_key: []
      tags:
        - auth
produces:
  - application/json
responses:
  ClearSessionResponse:
    description: |-
      A ClearSession response model
      This is used for returning response from clear session result
    schema:
      $ref: '#/definitions/ClearSessionResponseBody'
  GetProductList:
    description: |-
      A GetProductList response model
      This is used for getting Product List based on PublicationCode
    schema:
      $ref: '#/definitions/ListResponse'
  LoginResponse:
    description: |-
      A MySphLoginResponse response model
      This is used for returning response from login result
    schema:
      $ref: '#/definitions/LoginResponseBody'
  LogoutResponse:
    description: |-
      A MySphLogoutResponse response model
      This is used for returning response from logout result
    schema:
      $ref: '#/definitions/LogoutResponseBody'
  MySPHCheckDeviceResponse:
    description: |-
      A MySPHCheckDeviceResponse model
      this is used or returning response from check device result
    schema:
      $ref: '#/definitions/MySPHCheckDeviceResponseBody'
  RegisterResponse:
    description: |-
      A MySphRegisterResponse response model
      This is used for returning response from register result
    schema:
      $ref: '#/definitions/RegisterResponseBody'
  WebhookResponse:
    description: |-
      A WebhookResponse response model
      This is used for returning response from Webhook result
    schema:
      $ref: '#/definitions/WebhookResponseBody'
schemes:
  - http
  - https
swagger: "2.0"